### ISSUE TITLE
Assist: All teh assets

### ISSUE THREAD

**Issue by crogonint** [Caeora/Caeora-s-Maps-Tokens-Assets#5]
Greetings! As it just so happens, I've spent about a week sifting through your wesites resources (and other people's), and I was wondering if you would like me to help you fill in the cracks of your missing free resources?
Example: You have a handful or two of posts on Patreon that weren't tagged properly, or tagged at all. You have a handful of stuff on DeviantArt that didn't make it anywhere else, and a couple of items on the website aren't linked properly anywhere else. I recall one item I had to go to the Internet Archive to find.

I'm not finished archiving yet, I still have to sift through Twitch and Discord. Do you have a Reddit channel? It seems like the sort of thing you would have, but I haven't seen one. If it's listed under Blue Sword something or other, I'm not sure if I could find it intuitively either. Also, where did you post stuff prior to the old website and Deviant Art?

Anyway, main point of this is that I'd be more than happy to help you sort it all for the Foundry Community, I was gathering it up to be able to use it in Foundry and MapTool myself. :)

I'm posting this here, because even though I am a developer, I haven't done any coding in quite a long time. I'm not sure if you would prefer me to just submit missing resources to you to plug in, join this git, or open a sub of some sort. The git stuff seems a bit excessive, I would think that I could just sift through the resources and.... well, anyway, I just wanted to get your opinion on that. :)

**Comment by Caeora** [comment]
That is very nice of you to offer, and I am aware that a bunch of things are missing right now. I'm in the process of updating and adding content and more importantly making older content a little more consistent for use in VTT's. I've been around a while so many older maps were really made for print. If you would like to message me on on discord however I think we could work something out if you are still willing in order to update things! :) (You can find a link to my discord on my site)

**Comment by crogonint** [comment]
My apologies, I must have missed your earlier message. I'll try to find you
on your discord server later today. :)
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
